/** Core faculty roster (MAA Institute of Speech & Hearing). */
export type CoreFacultyMember = {
  name: string;
  designation: string;
  department: string;
  academicQualification: string;
  rehabilitationQualification: string;
  experience: string;
  rciRegNo: string;
  validTill: string;
  dateOfJoining: string;
};

export const CORE_FACULTY: CoreFacultyMember[] = [
  {
    name: "Dr. Aparna Ravichandran",
    designation: "Principal & Professor (AUD)",
    department: "Audiology",
    academicQualification:
      "M.Sc (ASLP), M.Sc (Psy), M.Phil (Psy), MBA (HRM), MA (Ling.), PGD in Ap. Ling., PhD",
    rehabilitationQualification: "M.Sc (ASLP), PhD",
    experience: "26 Years",
    rciRegNo: "A04594",
    validTill: "2025",
    dateOfJoining: "01/04/2023",
  },
  {
    name: "Mr. Gish Chacko",
    designation: "Associate Professor (AUD) & Head, Dept. of Audiology",
    department: "Audiology",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "12 Years",
    rciRegNo: "A-53857",
    validTill: "2028",
    dateOfJoining: "22/05/2019",
  },
  {
    name: "Mrs. Sandhra Sakariyas",
    designation: "Associate Professor (AUD)",
    department: "Audiology",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "11 Years",
    rciRegNo: "A-56065",
    validTill: "2028",
    dateOfJoining: "05/04/2021",
  },
  {
    name: "Dr. Sailaja Timmaraju",
    designation: "Associate Professor (AUD)",
    department: "Audiology",
    academicQualification: "M.Sc (Aud), D.AUD",
    rehabilitationQualification: "M.Sc (Aud)",
    experience: "15 yrs",
    rciRegNo: "",
    validTill: "",
    dateOfJoining: "08/04/2025",
  },
  {
    name: "Mrs. Archana Sasthikar",
    designation: "Associate Professor (SLP) & Head, Dept. of Speech Pathology",
    department: "SLP",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "16 Years",
    rciRegNo: "A-03520",
    validTill: "2028",
    dateOfJoining: "04/01/2022",
  },
  {
    name: "Mr. Hussam Farooq Akber",
    designation: "Assistant Professor (AUD)",
    department: "Audiology",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "5 Years",
    rciRegNo: "A-56099",
    validTill: "2025",
    dateOfJoining: "09/07/2018",
  },
  {
    name: "Mrs. Ambika Bose",
    designation: "Assistant Professor (SLP)",
    department: "SLP",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "3 Years",
    rciRegNo: "",
    validTill: "",
    dateOfJoining: "",
  },
  {
    name: "Mr. Vikas N.",
    designation: "Assistant Professor (SLP)",
    department: "SLP / AVT",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "7 Years",
    rciRegNo: "A-63308",
    validTill: "2026",
    dateOfJoining: "19/07/2017",
  },
  {
    name: "Mrs. Haritha Singaraju",
    designation: "Assistant Professor (SLP)",
    department: "SLP",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "",
    rciRegNo: "",
    validTill: "",
    dateOfJoining: "",
  },
  {
    name: "Mr. Mohd Shadab Mohiuddin",
    designation: "ASLP Grade I",
    department: "Audiology",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "3 Years",
    rciRegNo: "A-68035",
    validTill: "",
    dateOfJoining: "01/11/2019",
  },
  {
    name: "Mrs. Samata",
    designation: "Assistant Professor (Aud)",
    department: "Audiology",
    academicQualification: "M.Sc (ASLP)",
    rehabilitationQualification: "M.Sc (ASLP)",
    experience: "",
    rciRegNo: "",
    validTill: "",
    dateOfJoining: "",
  },
  {
    name: "Ms. Sirisha",
    designation: "ASLP Grade I",
    department: "SLP",
    academicQualification: "M.Sc (Audiology)",
    rehabilitationQualification: "M.Sc (Audiology)",
    experience: "2 Years",
    rciRegNo: "A84864",
    validTill: "08/11/2027",
    dateOfJoining: "08/12/2023",
  },
  {
    name: "Ms. Deepthi",
    designation: "ASLP Grade I",
    department: "Audiology",
    academicQualification: "M.Sc (Audiology)",
    rehabilitationQualification: "M.Sc (Audiology)",
    experience: "2 Years",
    rciRegNo: "A85301",
    validTill: "",
    dateOfJoining: "05/03/2024",
  },
];
